# Generated by Django 5.1.7 on 2025-03-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_history_uploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='user',
        ),
        migrations.DeleteModel(
            name='history',
        ),
        migrations.DeleteModel(
            name='uploads',
        ),
    ]
