# Generated by Django 5.1.7 on 2025-03-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_searchhistory_uploadedpdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedpdf',
            old_name='title',
            new_name='file_path',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uploadedpdf',
            name='file',
        ),
        migrations.RemoveField(
            model_name='uploadedpdf',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='subject',
            field=models.CharField(default='default subject', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='thumb_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
