# Generated by Django 5.1.7 on 2025-03-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_rename_title_uploadedpdf_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedpdf',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
