# Generated by Django 5.1.7 on 2025-03-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_alter_uploadedpdf_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedpdf',
            name='file_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='thumb_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
