# Generated by Django 5.1.7 on 2025-03-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_alter_uploadedpdf_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedpdf',
            name='file_path',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='thumb_path',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
